language: java
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
jdk:
  - openjdk8
  - openjdk11
install:
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    edge: true
    on:
      tags: true
      jdk: openjdk8
      branch: main

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: if4he3RF8XLr7pvQN9jJaoA+40b3PDObniux3YY7NnoRcOcV4N46hQn3i0CKpEpTT9E+gDyAuvd5NpCQW2VM4ePsfVXyY4wbWoXNpWCklKsNPk138PSa+zUZDfgyD8t7X3FHbGuZVlX3Jzu20WZikPdLYJoE6bU9TI9um57Mz8A=
